### ISSUE TITLE
Plans for Firefox, Safari support

### ISSUE THREAD

**Issue by saagarjha** [mash99/InTheLoop#1]
Are you planning to port this to Firefox and/or Safari?

**Comment by mash99** [comment]
That is possible - the code depends entirely on jQuery so yes it should work in any browser without much tweaking.

**Comment by akhil99** [comment]
To add on to what @mash99 said, while the central code will remain the same, it will have to be structured differently based on how firefox/safari allow 'extensions', or whatever their alternatives are.

For this reason, I don't think firefox/safari support is a high priority as of right now.
