### ISSUE TITLE
Doesn't work for one of my classes

### ISSUE THREAD

**Issue by danielhamg** [mash99/InTheLoop#16]
It works for all of my classes except one: 2nd period AP Calculus....I tried on 2 different computers and also reinstalling. Do you have an idea of what may be causing this?

**Comment by mash99** [comment]
Can you give me any more information about what format your grades are in? It would help if you could send a screenshot because there are a number of reasons for it not to work. Also, please report the error in Chrome's console (Command + Option + J (Mac) or Control + Shift + J (Windows/Linux))) along with the screenshot.

**Comment by danielhamg** [comment]
![screenshot 81](https://cloud.githubusercontent.com/assets/16365511/12187879/b6494230-b564-11e5-963b-47165094fc83.png)
![screenshot 82](https://cloud.githubusercontent.com/assets/16365511/12187882/b8747494-b564-11e5-9a1d-f73bc5f47aa4.png)
![screenshot 83](https://cloud.githubusercontent.com/assets/16365511/12187885/ba10fb7e-b564-11e5-9adf-84f7845aafb4.png)
![screenshot 84](https://cloud.githubusercontent.com/assets/16365511/12187910/f65858de-b564-11e5-8d6c-e517a63989ca.png)
As you can see, it works for APUSH just like it does for all the other classes EXCEPT AP Calc. It's strange. I also tried what you said and pressed ctrl+shift+J and the last image was what happened (it says 
"In The Loop failed to process grade entries (261)
chrome-extension://ppigcngidmooiiafkelbilbojiijffag/src/scripts/grades.js:1 In The Loop failed to start! (Line 457); e.length = 31; c.length = 3"

Maybe a thing to note is that my teacher gave an assessment in the beginning of the year ("readiness test") and it doesn't have a category so it doesn't affect our grade. Could that have anything to do with it?

**Comment by mash99** [comment]
The "readiness test" assignment is definitely the issue. In The Loop automatically disables itself if it might process grades incorrectly (in this case, it can't find the category information for the Readiness Test). In the future, In the Loop will be able to process stuff like this and should be able to tell the difference between extra credit and an assignment with no weightage.

Thanks for reporting this with so much detail! It helps a ton. If you find In The Loop useful be sure to share it!

**Comment by danielhamg** [comment]
Also, do you mind if you delete this or at least make it private somehow? I just don't want pictures of my grades floating around :D

**Comment by akhil99** [comment]
I don't think that's possible, but if you want we can edit your post and remove the screenshots. Does that work?

**Comment by danielhamg** [comment]
That would be great! And thanks so much!!!! Your app has really helped me :)

**Comment by mash99** [comment]
Removed the screenshots!
